name: pregnancy_ai_assistant
description: Pregnancy, postpartum, and baby nutrition AI assistant.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.40
  record: ^7.1.1
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^22.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  permission_handler: ^12.0.3
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
